//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNETCF.ORM
{
    using System;
    using OpenNETCF.ORM;
    
    
    [Entity(KeyScheme.None)]
    public class EmployeesTerritories
    {
        
        private static EmployeesTerritories ORM_CreateProxy(OpenNETCF.ORM.FieldAttributeCollection fields, System.Data.IDataReader results)
        {
            var item = new EmployeesTerritories();
foreach(var field in fields){
            var value = results[field.Ordinal];
switch(field.FieldName){
case "EmployeeID":
            // If this is a TimeSpan, use the commented line below
            // item.EmployeeID = (value == DBNull.Value) ? TimeSpan.MinValue; : new TimeSpan((long)value);
            item.EmployeeID = (value == DBNull.Value) ? 0 : (long)value;
            break;
case "TerritoryID":
            // If this is a TimeSpan, use the commented line below
            // item.TerritoryID = (value == DBNull.Value) ? TimeSpan.MinValue; : new TimeSpan((long)value);
            item.TerritoryID = (value == DBNull.Value) ? 0 : (long)value;
            break;
}
}
            return item;
        }
        
        private long m_employeeid;
        
        private long m_territoryid;
        
        private Territories m_refTerritories;
        
        private Employees m_refEmployees;
        
        [Field(IsPrimaryKey=true)]
        public long EmployeeID
        {
            get
            {
                return this.m_employeeid;
            }
            set
            {
                this.m_employeeid = value;
            }
        }
        
        [Field(IsPrimaryKey=true)]
        public long TerritoryID
        {
            get
            {
                return this.m_territoryid;
            }
            set
            {
                this.m_territoryid = value;
            }
        }
        
        [Reference(typeof(Territories), "TerritoryID", ReferenceType=ReferenceType.ManyToOne)]
        public Territories Territorie
        {
            get
            {
                return this.m_refTerritories;
            }
            set
            {
                this.m_refTerritories = value;
            }
        }
        
        [Reference(typeof(Employees), "EmployeeID", ReferenceType=ReferenceType.ManyToOne)]
        public Employees Employee
        {
            get
            {
                return this.m_refEmployees;
            }
            set
            {
                this.m_refEmployees = value;
            }
        }
    }
}
