//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNETCF.ORM
{
    using System;
    using OpenNETCF.ORM;
    
    
    [Entity(KeyScheme.None)]
    public class PreviousEmployees
    {
        
        private static PreviousEmployees ORM_CreateProxy(OpenNETCF.ORM.FieldAttributeCollection fields, System.Data.IDataReader results)
        {
            var item = new PreviousEmployees();
foreach(var field in fields){
            var value = results[field.Ordinal];
switch(field.FieldName){
case "EmployeeID":
            // If this is a TimeSpan, use the commented line below
            // item.EmployeeID = (value == DBNull.Value) ? TimeSpan.MinValue; : new TimeSpan((long)value);
            item.EmployeeID = (value == DBNull.Value) ? 0 : (long)value;
            break;
case "LastName":
            item.LastName = (value == DBNull.Value) ? null : (string)value;
            break;
case "FirstName":
            item.FirstName = (value == DBNull.Value) ? null : (string)value;
            break;
case "Title":
            item.Title = (value == DBNull.Value) ? null : (string)value;
            break;
case "TitleOfCourtesy":
            item.TitleOfCourtesy = (value == DBNull.Value) ? null : (string)value;
            break;
case "BirthDate":
            item.BirthDate = (value == DBNull.Value) ? null : (DateTime?)value;
            break;
case "HireDate":
            item.HireDate = (value == DBNull.Value) ? null : (DateTime?)value;
            break;
case "Address":
            item.Address = (value == DBNull.Value) ? null : (string)value;
            break;
case "City":
            item.City = (value == DBNull.Value) ? null : (string)value;
            break;
case "Region":
            item.Region = (value == DBNull.Value) ? null : (string)value;
            break;
case "PostalCode":
            item.PostalCode = (value == DBNull.Value) ? null : (string)value;
            break;
case "Country":
            item.Country = (value == DBNull.Value) ? null : (string)value;
            break;
case "HomePhone":
            item.HomePhone = (value == DBNull.Value) ? null : (string)value;
            break;
case "Extension":
            item.Extension = (value == DBNull.Value) ? null : (string)value;
            break;
case "Photo":
            item.Photo = (value == DBNull.Value) ? null : (byte[])value;
            break;
case "Notes":
            item.Notes = (value == DBNull.Value) ? null : (string)value;
            break;
case "PhotoPath":
            item.PhotoPath = (value == DBNull.Value) ? null : (string)value;
            break;
}
}
            return item;
        }
        
        private long m_employeeid;
        
        private string m_lastname;
        
        private string m_firstname;
        
        private string m_title;
        
        private string m_titleofcourtesy;
        
        private System.Nullable<System.DateTime> m_birthdate;
        
        private System.Nullable<System.DateTime> m_hiredate;
        
        private string m_address;
        
        private string m_city;
        
        private string m_region;
        
        private string m_postalcode;
        
        private string m_country;
        
        private string m_homephone;
        
        private string m_extension;
        
        private byte[] m_photo;
        
        private string m_notes;
        
        private string m_photopath;
        
        [Field(IsPrimaryKey=true)]
        public long EmployeeID
        {
            get
            {
                return this.m_employeeid;
            }
            set
            {
                this.m_employeeid = value;
            }
        }
        
        [Field()]
        public string LastName
        {
            get
            {
                return this.m_lastname;
            }
            set
            {
                this.m_lastname = value;
            }
        }
        
        [Field()]
        public string FirstName
        {
            get
            {
                return this.m_firstname;
            }
            set
            {
                this.m_firstname = value;
            }
        }
        
        [Field()]
        public string Title
        {
            get
            {
                return this.m_title;
            }
            set
            {
                this.m_title = value;
            }
        }
        
        [Field()]
        public string TitleOfCourtesy
        {
            get
            {
                return this.m_titleofcourtesy;
            }
            set
            {
                this.m_titleofcourtesy = value;
            }
        }
        
        [Field()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.m_birthdate;
            }
            set
            {
                this.m_birthdate = value;
            }
        }
        
        [Field()]
        public System.Nullable<System.DateTime> HireDate
        {
            get
            {
                return this.m_hiredate;
            }
            set
            {
                this.m_hiredate = value;
            }
        }
        
        [Field()]
        public string Address
        {
            get
            {
                return this.m_address;
            }
            set
            {
                this.m_address = value;
            }
        }
        
        [Field()]
        public string City
        {
            get
            {
                return this.m_city;
            }
            set
            {
                this.m_city = value;
            }
        }
        
        [Field()]
        public string Region
        {
            get
            {
                return this.m_region;
            }
            set
            {
                this.m_region = value;
            }
        }
        
        [Field()]
        public string PostalCode
        {
            get
            {
                return this.m_postalcode;
            }
            set
            {
                this.m_postalcode = value;
            }
        }
        
        [Field()]
        public string Country
        {
            get
            {
                return this.m_country;
            }
            set
            {
                this.m_country = value;
            }
        }
        
        [Field()]
        public string HomePhone
        {
            get
            {
                return this.m_homephone;
            }
            set
            {
                this.m_homephone = value;
            }
        }
        
        [Field()]
        public string Extension
        {
            get
            {
                return this.m_extension;
            }
            set
            {
                this.m_extension = value;
            }
        }
        
        [Field()]
        public byte[] Photo
        {
            get
            {
                return this.m_photo;
            }
            set
            {
                this.m_photo = value;
            }
        }
        
        [Field()]
        public string Notes
        {
            get
            {
                return this.m_notes;
            }
            set
            {
                this.m_notes = value;
            }
        }
        
        [Field()]
        public string PhotoPath
        {
            get
            {
                return this.m_photopath;
            }
            set
            {
                this.m_photopath = value;
            }
        }
    }
}
