//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591
namespace AFL.OSA.Models
{
	using OpenNETCF.ORM;


	[Entity(KeyScheme.None)]
	public partial class OSATestSettings
	{

		private int m_id;

		private string m_name;

		private string m_description;

		private int m_startingchannel;

		private int m_endingchannel;

		private double m_startingfrequency;

		private double m_endingfrequency;

		private double m_highpeakpowerthreshold;

		private double m_lowpeakpowerthreshold;

		private double m_lowosnrthreshold;

		private double m_highnoisepowerthreshold;

		private double m_frequencythreshold;

		private double m_highchannelpowerthreshold;

		private double m_lowchannelpowerthreshold;

		private bool m_showhighpowerpassfail;

		private bool m_showlowpowerpassfail;

		private bool m_showlowosnrpassfail;

		private bool m_showhighnoisepassfail;

		private bool m_showfrequencypassfail;

		private bool m_showhighchannelpowerpassfail;

		private bool m_showlowchannelpowerpassfail;

		private int m_healthychannelcolorargb;

		private int m_marginalchannelcolorargb;

		private int m_unhealthychannelcolorargb;

		private int m_osnrregioncolorargb;

		private int m_healthychannelregioncolorargb;

		private int m_unhealthychannelregioncolorargb;

		private int m_marginalchannelregioncolorargb;

		private int m_channelmarkercolorargb;

		private int m_totalpowerwarningcolorargb;

		private double m_peakpowerfailthreshold;

		private double m_highnoisethreshold;

		private double m_lowpowerthreshold;

		private double m_hightotalpowerthreshold;

		private double m_lowtotalpowerthreshold;

		private double m_healthfailthreshold;

		private double m_healthmarginalthreshold;

		private double m_healthlowpowerthreshold;

		private double m_healthlowosnrthreshold;

		private double m_healthfrequencythreshold;

		private bool m_showhightotalpowerwarning;

		private bool m_showlowtotalpowerwarning;

		private bool m_showchannels;

		private bool m_showpowerhighpassfail;

		private bool m_showpowerlowpassfail;

		private bool m_showosnrpassfail;

		private bool m_shownoisepassfail;

		private bool m_enablestartingfrequency;

		private bool m_enableendingfrequency;

		private double m_testpointpowerratiopercent;

		private int m_decimationfactorsave;

		private double m_endingwavelengthsave;

		private double m_startingwavelengthsave;

		private double m_testpointpowerratiodbsave;

		private bool m_showchannelnumbers;

		private int m_devicesettingsid;

		private int m_xaxistypeid;

		private int m_startendcontrolid;

		private int m_testpointpowerratiotypeid;

		private int m_channelplanid;

		[Field(IsPrimaryKey = true, SearchOrder = FieldSearchOrder.Ascending)]
		public int Id
		{
			get
			{
				return this.m_id;
			}
			set
			{
				this.m_id = value;
			}
		}

		[Field()]
		public string Name
		{
			get
			{
				return this.m_name;
			}
			set
			{
				this.m_name = value;
			}
		}

		[Field()]
		public string Description
		{
			get
			{
				return this.m_description;
			}
			set
			{
				this.m_description = value;
			}
		}

		[Field()]
		public int StartingChannel
		{
			get
			{
				return this.m_startingchannel;
			}
			set
			{
				this.m_startingchannel = value;
			}
		}

		[Field()]
		public int EndingChannel
		{
			get
			{
				return this.m_endingchannel;
			}
			set
			{
				this.m_endingchannel = value;
			}
		}

		[Field()]
		public double StartingFrequency
		{
			get
			{
				return this.m_startingfrequency;
			}
			set
			{
				this.m_startingfrequency = value;
			}
		}

		[Field()]
		public double EndingFrequency
		{
			get
			{
				return this.m_endingfrequency;
			}
			set
			{
				this.m_endingfrequency = value;
			}
		}

		[Field()]
		public double HighPeakPowerThreshold
		{
			get
			{
				return this.m_highpeakpowerthreshold;
			}
			set
			{
				this.m_highpeakpowerthreshold = value;
			}
		}

		[Field()]
		public double LowPeakPowerThreshold
		{
			get
			{
				return this.m_lowpeakpowerthreshold;
			}
			set
			{
				this.m_lowpeakpowerthreshold = value;
			}
		}

		[Field()]
		public double LowOsnrThreshold
		{
			get
			{
				return this.m_lowosnrthreshold;
			}
			set
			{
				this.m_lowosnrthreshold = value;
			}
		}

		[Field()]
		public double HighNoisePowerThreshold
		{
			get
			{
				return this.m_highnoisepowerthreshold;
			}
			set
			{
				this.m_highnoisepowerthreshold = value;
			}
		}

		[Field()]
		public double FrequencyThreshold
		{
			get
			{
				return this.m_frequencythreshold;
			}
			set
			{
				this.m_frequencythreshold = value;
			}
		}

		[Field()]
		public double HighChannelPowerThreshold
		{
			get
			{
				return this.m_highchannelpowerthreshold;
			}
			set
			{
				this.m_highchannelpowerthreshold = value;
			}
		}

		[Field()]
		public double LowChannelPowerThreshold
		{
			get
			{
				return this.m_lowchannelpowerthreshold;
			}
			set
			{
				this.m_lowchannelpowerthreshold = value;
			}
		}

		[Field()]
		public bool ShowHighPowerPassFail
		{
			get
			{
				return this.m_showhighpowerpassfail;
			}
			set
			{
				this.m_showhighpowerpassfail = value;
			}
		}

		[Field()]
		public bool ShowLowPowerPassFail
		{
			get
			{
				return this.m_showlowpowerpassfail;
			}
			set
			{
				this.m_showlowpowerpassfail = value;
			}
		}

		[Field()]
		public bool ShowLowOsnrPassFail
		{
			get
			{
				return this.m_showlowosnrpassfail;
			}
			set
			{
				this.m_showlowosnrpassfail = value;
			}
		}

		[Field()]
		public bool ShowHighNoisePassFail
		{
			get
			{
				return this.m_showhighnoisepassfail;
			}
			set
			{
				this.m_showhighnoisepassfail = value;
			}
		}

		[Field()]
		public bool ShowFrequencyPassFail
		{
			get
			{
				return this.m_showfrequencypassfail;
			}
			set
			{
				this.m_showfrequencypassfail = value;
			}
		}

		[Field()]
		public bool ShowHighChannelPowerPassFail
		{
			get
			{
				return this.m_showhighchannelpowerpassfail;
			}
			set
			{
				this.m_showhighchannelpowerpassfail = value;
			}
		}

		[Field()]
		public bool ShowLowChannelPowerPassFail
		{
			get
			{
				return this.m_showlowchannelpowerpassfail;
			}
			set
			{
				this.m_showlowchannelpowerpassfail = value;
			}
		}

		[Field()]
		public int HealthyChannelColorArgb
		{
			get
			{
				return this.m_healthychannelcolorargb;
			}
			set
			{
				this.m_healthychannelcolorargb = value;
			}
		}

		[Field()]
		public int MarginalChannelColorArgb
		{
			get
			{
				return this.m_marginalchannelcolorargb;
			}
			set
			{
				this.m_marginalchannelcolorargb = value;
			}
		}

		[Field()]
		public int UnhealthyChannelColorArgb
		{
			get
			{
				return this.m_unhealthychannelcolorargb;
			}
			set
			{
				this.m_unhealthychannelcolorargb = value;
			}
		}

		[Field()]
		public int OsnrRegionColorArgb
		{
			get
			{
				return this.m_osnrregioncolorargb;
			}
			set
			{
				this.m_osnrregioncolorargb = value;
			}
		}

		[Field()]
		public int HealthyChannelRegionColorArgb
		{
			get
			{
				return this.m_healthychannelregioncolorargb;
			}
			set
			{
				this.m_healthychannelregioncolorargb = value;
			}
		}

		[Field()]
		public int UnhealthyChannelRegionColorArgb
		{
			get
			{
				return this.m_unhealthychannelregioncolorargb;
			}
			set
			{
				this.m_unhealthychannelregioncolorargb = value;
			}
		}

		[Field()]
		public int MarginalChannelRegionColorArgb
		{
			get
			{
				return this.m_marginalchannelregioncolorargb;
			}
			set
			{
				this.m_marginalchannelregioncolorargb = value;
			}
		}

		[Field()]
		public int ChannelMarkerColorArgb
		{
			get
			{
				return this.m_channelmarkercolorargb;
			}
			set
			{
				this.m_channelmarkercolorargb = value;
			}
		}

		[Field()]
		public int TotalPowerWarningColorArgb
		{
			get
			{
				return this.m_totalpowerwarningcolorargb;
			}
			set
			{
				this.m_totalpowerwarningcolorargb = value;
			}
		}

		[Field()]
		public double PeakPowerFailThreshold
		{
			get
			{
				return this.m_peakpowerfailthreshold;
			}
			set
			{
				this.m_peakpowerfailthreshold = value;
			}
		}

		[Field()]
		public double HighNoiseThreshold
		{
			get
			{
				return this.m_highnoisethreshold;
			}
			set
			{
				this.m_highnoisethreshold = value;
			}
		}

		[Field()]
		public double LowPowerThreshold
		{
			get
			{
				return this.m_lowpowerthreshold;
			}
			set
			{
				this.m_lowpowerthreshold = value;
			}
		}

		[Field()]
		public double HighTotalPowerThreshold
		{
			get
			{
				return this.m_hightotalpowerthreshold;
			}
			set
			{
				this.m_hightotalpowerthreshold = value;
			}
		}

		[Field()]
		public double LowTotalPowerThreshold
		{
			get
			{
				return this.m_lowtotalpowerthreshold;
			}
			set
			{
				this.m_lowtotalpowerthreshold = value;
			}
		}

		[Field()]
		public double HealthFailThreshold
		{
			get
			{
				return this.m_healthfailthreshold;
			}
			set
			{
				this.m_healthfailthreshold = value;
			}
		}

		[Field()]
		public double HealthMarginalThreshold
		{
			get
			{
				return this.m_healthmarginalthreshold;
			}
			set
			{
				this.m_healthmarginalthreshold = value;
			}
		}

		[Field()]
		public double HealthLowPowerThreshold
		{
			get
			{
				return this.m_healthlowpowerthreshold;
			}
			set
			{
				this.m_healthlowpowerthreshold = value;
			}
		}

		[Field()]
		public double HealthLowOsnrThreshold
		{
			get
			{
				return this.m_healthlowosnrthreshold;
			}
			set
			{
				this.m_healthlowosnrthreshold = value;
			}
		}

		[Field()]
		public double HealthFrequencyThreshold
		{
			get
			{
				return this.m_healthfrequencythreshold;
			}
			set
			{
				this.m_healthfrequencythreshold = value;
			}
		}

		[Field()]
		public bool ShowHighTotalPowerWarning
		{
			get
			{
				return this.m_showhightotalpowerwarning;
			}
			set
			{
				this.m_showhightotalpowerwarning = value;
			}
		}

		[Field()]
		public bool ShowLowTotalPowerWarning
		{
			get
			{
				return this.m_showlowtotalpowerwarning;
			}
			set
			{
				this.m_showlowtotalpowerwarning = value;
			}
		}

		[Field()]
		public bool ShowChannels
		{
			get
			{
				return this.m_showchannels;
			}
			set
			{
				this.m_showchannels = value;
			}
		}

		[Field()]
		public bool ShowPowerHighPassFail
		{
			get
			{
				return this.m_showpowerhighpassfail;
			}
			set
			{
				this.m_showpowerhighpassfail = value;
			}
		}

		[Field()]
		public bool ShowPowerLowPassFail
		{
			get
			{
				return this.m_showpowerlowpassfail;
			}
			set
			{
				this.m_showpowerlowpassfail = value;
			}
		}

		[Field()]
		public bool ShowOsnrPassFail
		{
			get
			{
				return this.m_showosnrpassfail;
			}
			set
			{
				this.m_showosnrpassfail = value;
			}
		}

		[Field()]
		public bool ShowNoisePassFail
		{
			get
			{
				return this.m_shownoisepassfail;
			}
			set
			{
				this.m_shownoisepassfail = value;
			}
		}

		[Field()]
		public bool EnableStartingFrequency
		{
			get
			{
				return this.m_enablestartingfrequency;
			}
			set
			{
				this.m_enablestartingfrequency = value;
			}
		}

		[Field()]
		public bool EnableEndingFrequency
		{
			get
			{
				return this.m_enableendingfrequency;
			}
			set
			{
				this.m_enableendingfrequency = value;
			}
		}

		[Field()]
		public double TestPointPowerRatioPercent
		{
			get
			{
				return this.m_testpointpowerratiopercent;
			}
			set
			{
				this.m_testpointpowerratiopercent = value;
			}
		}

		[Field()]
		public int DecimationFactorSave
		{
			get
			{
				return this.m_decimationfactorsave;
			}
			set
			{
				this.m_decimationfactorsave = value;
			}
		}

		[Field()]
		public double EndingWavelengthSave
		{
			get
			{
				return this.m_endingwavelengthsave;
			}
			set
			{
				this.m_endingwavelengthsave = value;
			}
		}

		[Field()]
		public double StartingWavelengthSave
		{
			get
			{
				return this.m_startingwavelengthsave;
			}
			set
			{
				this.m_startingwavelengthsave = value;
			}
		}

		[Field()]
		public double TestPointPowerRatioDbSave
		{
			get
			{
				return this.m_testpointpowerratiodbsave;
			}
			set
			{
				this.m_testpointpowerratiodbsave = value;
			}
		}

		[Field()]
		public bool ShowChannelNumbers
		{
			get
			{
				return this.m_showchannelnumbers;
			}
			set
			{
				this.m_showchannelnumbers = value;
			}
		}

		[Field()]
		public int DeviceSettingsId
		{
			get
			{
				return this.m_devicesettingsid;
			}
			set
			{
				this.m_devicesettingsid = value;
			}
		}

		[Field()]
		public int XAxisTypeId
		{
			get
			{
				return this.m_xaxistypeid;
			}
			set
			{
				this.m_xaxistypeid = value;
			}
		}

		[Field()]
		public int StartEndControlId
		{
			get
			{
				return this.m_startendcontrolid;
			}
			set
			{
				this.m_startendcontrolid = value;
			}
		}

		[Field()]
		public int TestPointPowerRatioTypeId
		{
			get
			{
				return this.m_testpointpowerratiotypeid;
			}
			set
			{
				this.m_testpointpowerratiotypeid = value;
			}
		}

		[Field()]
		public int ChannelPlanId
		{
			get
			{
				return this.m_channelplanid;
			}
			set
			{
				this.m_channelplanid = value;
			}
		}
	}
}
#pragma warning restore 1591
